##########################################################################################
## Plot cell type enrichment results generated by ASD_CellTypeEnrichmentAnalysis.py
##
## Author: Yu-Han Hsu
##########################################################################################

rm(list=ls())

library(ggplot2)
library(data.table)


# ----------------------------------------------------------------------------------------
# overlap enrichment between network and ASD-DEGs

degDf <- read.table('../output/ASD_scDegEnrichment.txt',
	header=T,sep="\t",stringsAsFactors=F)
degDf$Test <- factor(degDf$Test, levels=c('Global','Conditional'))

# original cell type order from Velmehsev2019
cellOrder <- unique(degDf$CellType)

# fix celltype order in plot and add gene count per cell type in ()
degCountDf <- subset(degDf,Test=='Global' &	
	Dataset=='COMBINED')[,c('CellType','DegType','DegCount')]
degDf$OrigDegCount <- degCountDf$DegCount[match(degDf$CellType,degCountDf$CellType)]
for (i in 1:nrow(degCountDf)) {
	degDf$OrigDegCount[which(degDf$CellType==degCountDf$CellType[i] &
		degDf$DegType==degCountDf$DegType[i])] <- degCountDf$DegCount[i]
}

degDf$CellType <- paste(degDf$CellType,' (',degDf$OrigDegCount,')',sep='')
degDf$CellType <- factor(degDf$CellType, levels=rev(unique(degDf$CellType)))

# bar plot color based on significance:
# Bonferroni = 0.05/17 (adjusting for number of cell types)
nCT <- length(cellOrder)
bonfStr <- paste('P < 0.05/',nCT,sep='')
degDf$Significance <- ifelse(degDf$P < 0.05,'P < 0.05','None')
degDf$Significance[degDf$P<0.05/nCT] <- bonfStr
degDf$Significance <- factor(degDf$Significance, levels=c('None','P < 0.05',bonfStr))

# overlap count label for nominally significant results
degDf$SigText <- ifelse(degDf$P < 0.05,degDf$OverlapCount,'')


# ----------------------------------------------------------------------------------------
# overlap enrichment between network and genes expressed in >50% of cells in cell type

expDf <- read.table('../output/ASD_scExpEnrichment.txt',
	header=T,sep="\t",stringsAsFactors=F)

expDf$Test <- factor(expDf$Test, levels=c('Global','Conditional'))

# fix celltype order in plot and add gene count per cell type
expDf$CellType <- factor(expDf$CellType,levels=cellOrder)
expDf <- expDf[order(expDf$CellType),]
expCountDf <- subset(expDf,Test=='Global' & 
	Dataset=='COMBINED')[,c('CellType','ExpCount')]
expDf$OrigExpCount <- expCountDf$ExpCount[match(expDf$CellType,expCountDf$CellType)] 

expDf$CellType <- paste(expDf$CellType,' (',expDf$OrigExpCount,')',sep='')
expDf$CellType <- factor(expDf$CellType, levels=rev(unique(expDf$CellType)))

# bar plot color based on significance:
# Bonferroni = 0.05/17 (adjusting for number of cell types)
expDf$Significance <- ifelse(expDf$P < 0.05,'P < 0.05','None')
expDf$Significance[expDf$P<0.05/nCT] <- bonfStr 
expDf$Significance <- factor(expDf$Significance, levels=c('None','P < 0.05',bonfStr))

# overlap count label for nominally significant results
expDf$SigText <- ifelse(expDf$P < 0.05,expDf$OverlapCount,'')


# ----------------------------------------------------------------------------------------
# facet (Global vs Conditional) bar plots

pdf('../output/ASD_CellTypeEnrichment_FacetBarPlots.pdf',height=3.2,width=4.5)

# expressed genes results
ggplot(subset(expDf,Dataset=='COMBINED'),aes(x=CellType,y=-log10(P),fill=Significance)) + 
facet_wrap(~Test) + geom_col(show.legend=F) +

geom_hline(yintercept=-log10(0.05),linetype='dashed',size=0.25) +
geom_hline(yintercept=-log10(0.05/nCT),linetype='dashed',size=0.25) +

geom_text(aes(label=SigText),hjust=-0.1,size=3) +

scale_fill_manual(values=c('None'='black','P < 0.05'='sienna1','P < 0.05/17'='red')) +
scale_y_continuous(expand=expansion(mult=c(0,0.2),add=c(0,0))) +

xlab('Cell type') + ylab(bquote(-log[10]*"("*italic(.("P"))*"-value)")) +
ggtitle('COMBINED: >50% expressed genes') +
coord_flip() + theme_bw() + theme(plot.title=element_text(size=9),
	axis.title=element_text(size=9),axis.text=element_text(size=8))

# DEGs results
for (dType in unique(degDf$DegType)) {
	
	print(
	ggplot(subset(degDf,Dataset=='COMBINED' & DegType==dType),
		aes(x=CellType,y=-log10(P),fill=Significance)) +
	facet_wrap(~Test) + geom_col(show.legend=F) + 
	
	geom_hline(yintercept=-log10(0.05),linetype='dashed',size=0.25) +
	geom_hline(yintercept=-log10(0.05/nCT),linetype='dashed',size=0.25) +
	
	geom_text(aes(label=SigText),hjust=-0.1,size=3) +
	
	scale_fill_manual(values=c('None'='black','P < 0.05'='sienna1','P < 0.05/17'='red')) +
	scale_y_continuous(expand=expansion(mult=c(0,0.2),add=c(0,0))) +
	
	xlab('Cell type') + ylab(bquote(-log[10]*"("*italic(.("P"))*"-value)")) +
	ggtitle(paste('COMBINED: ',dType,' DEGs',sep='')) +
	coord_flip() + theme_bw() + theme(plot.title=element_text(size=9),
		axis.title=element_text(size=9),axis.text=element_text(size=8))
	)
}

dev.off()


# ----------------------------------------------------------------------------------------
# single panel bar plots

pdf('../output/ASD_CellTypeEnrichment_SingleBarPlots.pdf',width=3,height=3)

# expressed genes results
# conditional test
subDf <- subset(expDf,Dataset=='COMBINED'&Test=='Conditional')
subDf$CellType <- factor(subDf$CellType,
	levels=rev(as.character(subDf$CellType[order(subDf$P)])))

ggplot(subDf,aes(x=CellType,y=-log10(P),fill=Significance)) + geom_col() +

geom_hline(yintercept=-log10(0.05),linetype='dashed',size=0.25) +
geom_hline(yintercept=-log10(0.05/nCT),linetype='dashed',size=0.25) +

geom_text(aes(label=SigText),hjust=-0.1,size=3) +

scale_fill_manual(values = c('None'='black','P < 0.05'='sienna1','P < 0.05/17'='red')) +
scale_y_continuous(expand=expansion(mult=c(0,0.2),add=c(0,0))) +

xlab('Cell type') + ylab(bquote(-log[10]*"("*italic(.("P"))*"-value)")) +
ggtitle('Conditional, 50PercExp') +
coord_flip() + theme_bw() + theme(legend.position='none',plot.title=element_text(size=9),
	axis.title=element_text(size=9),axis.text=element_text(size=8))

# global test
subDf <- subset(expDf,Dataset=='COMBINED'&Test=='Global')
subDf$CellType <- factor(subDf$CellType, 
	levels=rev(as.character(subDf$CellType[order(subDf$P)])))

ggplot(subDf,aes(x=CellType,y=-log10(P),fill=Significance)) + geom_col() +

geom_hline(yintercept=-log10(0.05),linetype='dashed',size=0.25) +
geom_hline(yintercept=-log10(0.05/nCT),linetype='dashed',size=0.25) +

geom_text(aes(label=SigText),hjust=-0.1,size=3) +

scale_fill_manual(values = c('None'='black','P < 0.05'='sienna1','P < 0.05/17'='red')) +
scale_y_continuous(expand=expansion(mult=c(0,0.2),add=c(0,0))) +

xlab('Cell type') + ylab(bquote(-log[10]*"("*italic(.("P"))*"-value)")) +
ggtitle('Global, 50PercExp') +
coord_flip() + theme_bw() + theme(legend.position='none',plot.title=element_text(size=9),
	axis.title=element_text(size=9),axis.text=element_text(size=8))


# All DEGs results
# conditional test
subDf <- subset(degDf,Dataset=='COMBINED'&Test=='Conditional'&DegType=='All')
subDf$CellType <- factor(subDf$CellType, 
	levels=rev(as.character(subDf$CellType[order(subDf$P)])))

ggplot(subDf,aes(x=CellType,y=-log10(P),fill=Significance)) + geom_col() +

geom_hline(yintercept=-log10(0.05),linetype='dashed',size=0.25) +
geom_hline(yintercept=-log10(0.05/nCT),linetype='dashed',size=0.25) +

geom_text(aes(label=SigText),hjust=-0.1,size=3) +

scale_fill_manual(values = c('None'='black','P < 0.05'='sienna1','P < 0.05/17'='red')) +
scale_y_continuous(expand=expansion(mult=c(0,0.2),add=c(0,0))) +

xlab('Cell type') + ylab(bquote(-log[10]*"("*italic(.("P"))*"-value)")) +
ggtitle('Conditional, All DEGs') +
coord_flip() + theme_bw() + theme(legend.position='none',plot.title=element_text(size=9),
	axis.title=element_text(size=9),axis.text=element_text(size=8))

# global test
subDf <- subset(degDf,Dataset=='COMBINED'&Test=='Global'&DegType=='All')
subDf$CellType <- factor(subDf$CellType, 
	levels=rev(as.character(subDf$CellType[order(subDf$P)])))

ggplot(subDf,aes(x=CellType,y=-log10(P),fill=Significance)) + geom_col() +

geom_hline(yintercept=-log10(0.05),linetype='dashed',size=0.25) +
geom_hline(yintercept=-log10(0.05/nCT),linetype='dashed',size=0.25) +

geom_text(aes(label=SigText),hjust=-0.1,size=3) +

scale_fill_manual(values = c('None'='black','P < 0.05'='sienna1','P < 0.05/17'='red')) +
scale_y_continuous(expand=expansion(mult=c(0,0.2),add=c(0,0))) +

xlab('Cell type') + ylab(bquote(-log[10]*"("*italic(.("P"))*"-value)")) +
ggtitle('Global, All DEGs') +
coord_flip() + theme_bw() + theme(legend.position='none',plot.title=element_text(size=9),
	axis.title=element_text(size=9),axis.text=element_text(size=8))

dev.off()

